"""Dependency-light interface implemented only by gateway adapters."""
from typing import Protocol, runtime_checkable

from kdn_server.contracts.cache_service import (
    ArtifactRequest, CacheServiceResponse, CancelOperationRequest,
    GetOperationStatusRequest, LookupTokensRequest, OperationIntentRequest,
)
from .capabilities import CapabilitySnapshot


@runtime_checkable
class LMCacheGateway(Protocol):
    def discover_capabilities(self) -> CapabilitySnapshot: ...
    def lookup_artifact(self, request: ArtifactRequest) -> CacheServiceResponse: ...
    def lookup_tokens(self, request: LookupTokensRequest) -> CacheServiceResponse: ...
    def get_cache_observation(self, request: ArtifactRequest) -> CacheServiceResponse: ...
    def submit_operation(self, request: OperationIntentRequest) -> CacheServiceResponse: ...
    def get_operation_status(self, request: GetOperationStatusRequest) -> CacheServiceResponse: ...
    def cancel_operation(self, request: CancelOperationRequest) -> CacheServiceResponse: ...
    def get_endpoints(self) -> CacheServiceResponse: ...
    def get_tier_adapter_summary(self) -> CacheServiceResponse: ...
    def get_maintenance_status(self) -> CacheServiceResponse: ...
