"""Dependency-light interface implemented only by gateway adapters."""
from typing import Protocol, runtime_checkable

from kdn_server.contracts.cache_service import (
    ArtifactRequest, CancelOperationRequest, CancelOperationResponse,
    GetCacheObservationResponse, GetLMCacheEndpointsRequest, GetLMCacheEndpointsResponse,
    GetMaintenanceStatusRequest, GetMaintenanceStatusResponse, GetOperationStatusRequest,
    GetOperationStatusResponse, GetTierAndAdapterSummaryRequest,
    GetTierAndAdapterSummaryResponse, LookupArtifactResponse, LookupTokensRequest,
    LookupTokensResponse, OperationIntentRequest, OperationResponse,
)
from .capabilities import CapabilitySnapshot


@runtime_checkable
class LMCacheGateway(Protocol):
    def discover_capabilities(self) -> CapabilitySnapshot: ...
    def lookup_artifact(self, request: ArtifactRequest) -> LookupArtifactResponse: ...
    def lookup_tokens(self, request: LookupTokensRequest) -> LookupTokensResponse: ...
    def get_cache_observation(self, request: ArtifactRequest) -> GetCacheObservationResponse: ...
    def submit_operation(self, request: OperationIntentRequest) -> OperationResponse: ...
    def get_operation_status(self, request: GetOperationStatusRequest) -> GetOperationStatusResponse: ...
    def cancel_operation(self, request: CancelOperationRequest) -> CancelOperationResponse: ...
    def get_endpoints(self, request: GetLMCacheEndpointsRequest) -> GetLMCacheEndpointsResponse: ...
    def get_tier_adapter_summary(self, request: GetTierAndAdapterSummaryRequest) -> GetTierAndAdapterSummaryResponse: ...
    def get_maintenance_status(self, request: GetMaintenanceStatusRequest) -> GetMaintenanceStatusResponse: ...
