"""Temporary identity-preserving compatibility API for CacheRoute v1 contracts."""
from cacheroute.contracts.v1.common import (ContractModel, GATEWAY_CONTRACT_VERSION, GatewayTargetedRequest,
    KDN_CONTRACT_VERSION, SupportState, TokenInput, TokenReference, VersionedMessage)
from cacheroute.contracts.v1.errors import ContractError, ContractErrorDetail, OutcomeCode
from cacheroute.contracts.v1.knowledge import (KnowledgeDescriptor, KnowledgeResponse, ListCompatibleArtifactsRequest,
    ListCompatibleArtifactsResponse, QueryArtifactCompatibilityRequest,
    QueryArtifactCompatibilityResponse, RegisterKnowledgeRequest, RegisterKnowledgeResponse,
    ReportRequestOutcomeRequest, ReportRequestOutcomeResponse, ResolveKnowledgeRequest,
    ResolveKnowledgeResponse, UpdateKnowledgeRequest, UpdateKnowledgeResponse)
from cacheroute.contracts.v1.cache_service import (AdapterSummary, ArtifactRequest,
    CancelOperationRequest, CancelOperationResponse, CapacityUsageObservation,
    CreateClearIntentRequest, CreateClearIntentResponse, CreatePinIntentRequest,
    CreatePinIntentResponse, CreatePrefetchIntentRequest, CreatePrefetchIntentResponse,
    CreateRebuildIntentRequest, CreateRebuildIntentResponse, CreateUnpinIntentRequest,
    CreateUnpinIntentResponse, GetCacheObservationRequest, GetCacheObservationResponse,
    GetLMCacheEndpointsRequest, GetLMCacheEndpointsResponse, GetMaintenanceStatusRequest,
    GetMaintenanceStatusResponse, GetOperationStatusRequest, GetOperationStatusResponse,
    GetTierAndAdapterSummaryRequest, GetTierAndAdapterSummaryResponse,
    LookupArtifactRequest, LookupArtifactResponse, LookupTokensRequest, LookupTokensResponse,
    CacheServiceResponse, GatewayTargetedResponse, INTENT_OPERATION_TYPES,
    MaintenanceSummary, OperationIntentRequest, OperationResponse, SummaryBase, TierLevel,
    TierSummary, TokenCoverage)

__all__ = [
    "KDN_CONTRACT_VERSION", "GATEWAY_CONTRACT_VERSION", "ContractModel", "VersionedMessage",
    "GatewayTargetedRequest", "SupportState", "TokenReference", "TokenInput", "OutcomeCode",
    "ContractErrorDetail", "ContractError", "KnowledgeDescriptor",
    "KnowledgeResponse", "RegisterKnowledgeRequest", "RegisterKnowledgeResponse",
    "UpdateKnowledgeRequest", "UpdateKnowledgeResponse", "ResolveKnowledgeRequest",
    "ResolveKnowledgeResponse", "ListCompatibleArtifactsRequest", "ListCompatibleArtifactsResponse",
    "QueryArtifactCompatibilityRequest", "QueryArtifactCompatibilityResponse",
    "ReportRequestOutcomeRequest", "ReportRequestOutcomeResponse", "ArtifactRequest",
    "GetCacheObservationRequest", "LookupArtifactRequest", "LookupTokensRequest",
    "OperationIntentRequest", "CreatePrefetchIntentRequest", "CreatePinIntentRequest",
    "CreateUnpinIntentRequest", "CreateClearIntentRequest", "CreateRebuildIntentRequest",
    "GetOperationStatusRequest", "CancelOperationRequest", "GetLMCacheEndpointsRequest",
    "GetTierAndAdapterSummaryRequest", "GetMaintenanceStatusRequest", "TokenCoverage",
    "SummaryBase", "AdapterSummary", "TierLevel", "CapacityUsageObservation", "TierSummary",
    "MaintenanceSummary", "CacheServiceResponse", "GatewayTargetedResponse",
    "OperationResponse", "INTENT_OPERATION_TYPES", "GetCacheObservationResponse",
    "LookupArtifactResponse", "LookupTokensResponse",
    "CreatePrefetchIntentResponse", "CreatePinIntentResponse", "CreateUnpinIntentResponse",
    "CreateClearIntentResponse", "CreateRebuildIntentResponse", "GetOperationStatusResponse",
    "CancelOperationResponse", "GetLMCacheEndpointsResponse", "GetTierAndAdapterSummaryResponse",
    "GetMaintenanceStatusResponse",
]
